### ISSUE TITLE
Capacitor iOS log INVALID

### ISSUE THREAD

**Issue by ElLelero** [bugfender/cordova-plugin-bugfender#14]
Hi,
I'm attempting to install this plugin in a Ionic 6 + Capacitor project.
Since I'm using Capacitor, I ran the command:
`npm install cordova-plugin-bugfender`
and then manually edited the ios/App/App/Info.plist file for iOS and the android/app/src/main/res/values/strings.xml file for Android with the app key and automatic variables.

I also added the pod reference in the Podfile for iOS:
`pod 'BugfenderSDK', '~> 1.9.2'`
and ran the commands:
`pod repo update`
`pod install`

On Android, the plugin works fine, I can see the custom logs in the Dashboard.

On iOS, I receive the output message:
"To Native Cordova ->  Bugfender log INVALID"
and cannot receive any log from the device.

Is the plugin compatible with Capacitor? Do I need additional configuration?

Thanks in advance, best regards.

**Comment by jgimenez** [comment]
Hi, the Capacitor documentation mentions Cordova plugins are supported but we have not tested this.

We're not officially supporting Capacitor at the moment, although we're working on a Capacitor plugin that should be published in 2022 Q3.

**Comment by jgimenez** [comment]
Hi @ElLelero , the Capacitor SDK is on its way! You can help us test the release candidate here: `@bugfender/capacitor`

We're planning to release it in GA in a couple of weeks, if everything goes as planned.

**Comment by ElLelero** [comment]
Thanks for the update, I will try it out in the next weeks.

**Comment by j-leist** [comment]
> Hi @ElLelero , the Capacitor SDK is on its way! You can help us test the release candidate here: `@bugfender/capacitor`
> 
> We're planning to release it in GA in a couple of weeks, if everything goes as planned.

Using @bugfender/capacitor release candidate. Showing in logs that "Device key "user_email" set" and no errors reported but not seeing the logs actually in the dashboard. As a test I am using "Bugfender.log('Hello world!');" I can see it in the console log in Xcode but not in the Bugfender dashboard

**Comment by jgimenez** [comment]
Thanks, our iOS engineers will give it a look

**Comment by j-leist** [comment]
@jgimenez Perfect thank you - I am using the latest rc2 not that was updated today - Android working perfectly but no joy on iOS. I'll keep checking for updates :)

**Comment by jgimenez** [comment]
@j-leist could you please post an example of non-working code, or contact us at support so we can debug the project with you?

**Comment by j-leist** [comment]
@jgimenez Sure so importing with:

`import { Bugfender } from '@bugfender/sdk';`

And then running Init as:

```
Bugfender.init({
                appKey: 'XXXXXXXXX',
                overrideConsoleMethods: true,
                printToConsole: true,
                registerErrorHandler: true,
                // version: '',
                // build: '',
            });
```

Working perfectly on Android, iOS though shows in the Xcode console that the device key is set when we use  Bugfender.setDeviceKey('user_email', user.profile.email); but nothing actually being sent to Bugfender

Package I am using is "@bugfender/capacitor": "^1.0.0-rc.2",

Thanks in advance

**Comment by jgimenez** [comment]
Ah, I see. This has been fixed in `1.0.0-rc.3`. Could you please try with the latest rc? Thanks!

**Comment by j-leist** [comment]
@jgimenez Thanks - actually, as I sent the last message I noticed the update, I updated to rc3 but still the same I'm afraid

**Comment by j-leist** [comment]
@jgimenez Oddly have the same for Android now - it is however passing some information up to BugFender dashboard, I tested this by changing the app version number that is passed back and this updated but no logs being sent back.

Is there a support email I can use?

**Comment by franmontiel** [comment]
Hi @j-leist, would it be possible for you to provide a sample project that reproduces your issue? (be sure to remove any app key that you are using prior sharing). Thanks

**Comment by j-leist** [comment]
@franmontiel Happy to fire over the full project to you if that will help?

**Comment by j-leist** [comment]
@franmontiel I emailed you, hope that's ok :)

**Comment by franmontiel** [comment]
@j-leist yes, please send me the project that you want that reproduces the issue (preferably a sample project or a project that does not have proprietary code), you can send it to me by e-mail if you want.

Thanks.

**Comment by j-leist** [comment]
@franmontiel Sorry for the delay, I have just emailed you a sample project that recreates the issue :)

**Comment by franmontiel** [comment]
Hi @j-leist, thanks for sending us the sample project. We'll take a look as soon as possible.

**Comment by j-leist** [comment]
@franmontiel Perfect thank you - feel free to email me directly if you need me to test anything :)

**Comment by j-leist** [comment]
@franmontiel quick update - I noticed there was a new version released out today - still the same issue with that on iOS though I'm afraid.

**Comment by j-leist** [comment]
@franmontiel Just wanted to check in on this to see if you have had a chance to review? We're now live with the latest version but only receiving logs for Android is causing a bit of an issue

**Comment by franmontiel** [comment]
@j-leist we already tested it and found the issue. We will inform you as soon as we have the fix implemented. Thanks for your patience

**Comment by j-leist** [comment]
@franmontiel awesome, thanks :)

**Comment by franmontiel** [comment]
@j-leist good news! We did some changes at the backend level and now the plugin works on iOS without issues.

There is no need of updating the dependency, it will work from now on without any change in your code.

**Comment by j-leist** [comment]
Excellent! thanks @franmontiel

**Comment by j-leist** [comment]
@franmontiel just tested this - it's working in a sense that it now shows the device in the dashboard and passes the user info etc. - it will say when last seen. But there are no actual logs pushing up still that I can see. I'm going to test on that sample project I sent over too and confirm it's also the same there.

**Comment by jgimenez** [comment]
@j-leist who are you writing the logs? Are you writing them with `console.log()` or `bugfender.log()`?

**Comment by j-leist** [comment]
@jgimenez using console.log mostly - it actually all seems to be working ok now, I think perhaps it was just the delay but we're looking good :)

Thanks to the team for looking in to it.

**Comment by jgimenez** [comment]
Ok, great to hear! Closing this, then. If there's anything else you need, please let us know.
